import 'articulos.dart';

class Lista {
  static List<Articulos> operadores = [
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "11:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "12:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "13:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "14:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "15:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "16:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "17:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "18:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "19:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "24:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    //
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "08:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "11:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "12:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "13:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "14:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "15:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "16:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "17:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "18:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La Granjita",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "19:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "11:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "12:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "13:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "15:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "16:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "17:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "18:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "19:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "24:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Ruleta Activa",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "24:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
//
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "11:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "12:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "13:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "14:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "15:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "16:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "17:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "18:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "19:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Chance Con Animalitos",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "24:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    //
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "09:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "10:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "11:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "12:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "13:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "14:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "15:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "16:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "17:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "18:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "19:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Rey",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "24:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),

//

    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "11:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "12:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "13:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "14:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "15:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "16:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "17:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "18:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "19:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Selva Plus",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "24:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),

//
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "11:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "12:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "13:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "14:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "15:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "16:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "17:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "18:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "19:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Guacharo Activo",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "24:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),

//
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "09:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "10:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "11:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "12:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "13:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "14:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "15:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "16:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "17:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "18:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "19:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Jungla Millionaria",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "24:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),

//
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "09:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "10:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "11:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "12:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "13:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "14:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "15:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "16:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "17:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "18:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "19:10",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "La-Ricachona",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "24:00",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "08:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "09:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "10:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "11:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "12:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "13:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "14:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "15:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "16:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "17:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "18:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
    Articulos(
      operador: "Lotto Activo RD  Int",
      numero: "",
      urlimage: "",
      nombre: "matos",
      hora: "19:30",
      fecha: DateTime.now().toString().substring(0, 10),
    ),
  ];
}
